version: "3.8"

services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    networks:
      - fastiship_network
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
      POSTGRES_HOST_AUTH_METHOD: trust

  api:
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    depends_on:
      - postgres
    ports:
      - 3100:3100
    volumes:
      - ./apps/api:/app/apps/api
      - ./packages/database/prisma:/app/packages/database/prisma  # Mount correct prisma directory
      - /app/apps/api/node_modules
    command: >
      sh -c "
        until pg_isready -h postgres -U postgres -d mydb; do
          sleep 1;
        done;
        npx prisma db push --schema=/app/packages/database/prisma/schema.prisma && npm run start
      "
    environment:
      PORT: 3100
      DATABASE_URL: postgresql://postgres:password@host.docker.internal:5432/mydb?schema=public

    networks:
      - fastiship_network

  web:
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./apps/web:/app/apps/web
      - /app/apps/web/node_modules
    command: npm run start
    env_file:
      - ./apps/web/.env.local
    environment:
      PORT: 3000
      DATABASE_URL: postgresql://postgres:password@host.docker.internal:5432/mydb?schema=public

networks:
  fastiship_network:
    external: true
